name: transactions
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  intl: ^0.18.1
  redux: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
          weight: 400
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
